#!/bin/sh

echo "Removing the application..."
prefix=$(which jsnmpwalker | sed 's|/bin/.*||')
sudo rm -f $prefix/bin/jsnmpwalker
sudo rm -rf /Library/JSNMPWalker
sudo rm -rf /Applications/JSNMPWalker.app
echo "The application is uninstalled"
